 Install (if not already installed)
 !pip install numpy

 Import

In [3]:
import numpy as np

#Step 2: Creating Arrays
#1D Array

In [4]:
arr1 = np.array([1, 2, 3])

#2D Array

In [5]:
arr2 = np.array([[1, 2], [3, 4]])

# Special Arrays

In [6]:
np.zeros((2, 3))     # 2x3 array of zeros
np.ones((3, 3))      # 3x3 array of ones
np.eye(3)            # 3x3 Identity matrix
np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5) # 5 points between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Step 3: Indexing & Slicing

1D Indexing

In [7]:
arr = np.array([10, 20, 30, 40])
print(arr[0])      # 10
print(arr[-1])     # 40


10
40


# 2D Indexing

In [8]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[0, 1])  # Row 0, Column 1 = 2


2


# Slicing

In [12]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])    # [20 30 40]

[20 30 40]


# Step 4: Array Operations

In [13]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Element-wise operations
print(a + b)  # [11 22 33]
print(a * b)  # [10 40 90]
print(a ** 2) # [1 4 9]

# Mathematical functions
np.sum(a)
np.mean(a)
np.max(a)


[11 22 33]
[10 40 90]
[1 4 9]


np.int64(3)

# Step 5: Broadcasting

Broadcasting allows NumPy to do operations on arrays of different shapes.

##Example 1: Adding a scalar to an array##

In [14]:
a = np.array([1, 2, 3])
print(a + 10)   # [11 12 13]


[11 12 13]


# Example 2: 2D + 1D array

In [15]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(A + b)
# Output:
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]


# Step 6: Shape & Reshape

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)        # (2, 3)
print(arr.reshape(3, 2))  # Change shape to 3 rows, 2 columns


(2, 3)
[[1 2]
 [3 4]
 [5 6]]


# Step 7: Useful Array Methods

In [21]:
arr = np.array([5, 3, 1, 4, 2])

np.sort(arr)      # [1 2 3 4 5]
np.argsort(arr)   # [2 4 1 3 0] → indices that would sort array
np.unique(arr)    # [1 2 3 4 5]


array([1, 2, 3, 4, 5])